Change document structure
robot-lab/judyst-main-web-service pull request #127
Opened 2018-11-22 17:57 UTC by danila19991

# Pull Request

**ВАЖНО: Пожалуйста, не создавайте Pull Request, если не созданы issues, которые Ваш PR решает.**

## Описание

*Для внесения изменений в основные ветки нужно получить разрешения от тимлидов команд или соответствующих ревьюверов Ваших репозиториев.*

1, Изменил модель документа в соответствии со 2 задачей

## Тестовый план

Покажите, что Ваш код действительно безопасный. Обязательно проверьте, чтобы изменения проходили CI и не ломали имеющийся код.

## Закрытые issues

closes #126 
closes #124

2018-11-22 18:48 UTC, mehwhatever0 commented
В text_source_url для положений будет храниться позиция в сохраненном html, например 
![image](https://user-images.githubusercontent.com/43314216/48918837-39668c00-eea0-11e8-9f23-d3df56578379.png)

Не возникнет ли проблем с тем, что его тип задан как URLField?

2018-11-22 20:23 UTC, navolotsky requested changes
core/models.py
26 строка
заменить absolute_path = models.TextField(blank=False)
на absolute_path = models.TextField()

2018-11-22 20:23 UTC, navolotsky commented on core/models.py
> +    absolute_path = models.TextField(blank=False)
Необязательное поле, у КСРФ его нет.

2018-11-22 21:31 UTC, navolotsky approved these changes

2018-11-22 21:39 UTC, Vasar007 commented on core/tests/test_utils/test_link_utils.py
> +@pytest.mark.skip
Что потом будешь делать с этим кодом?

2018-11-22 21:39 UTC, Vasar007 commented on core/tests/test_views/search_view_set/test_views_search.py
> +@pytest.mark.skip
Аналогичный вопрос.

2018-11-22 21:44 UTC, danila19991 commented on core/tests/test_utils/test_link_utils.py
> +@pytest.mark.skip
когда стабилизируется api для поиска будут использованы в тестировании

2018-11-22 21:44 UTC, danila19991 commented on core/tests/test_views/search_view_set/test_views_search.py
> +@pytest.mark.skip
аналогично

2018-11-22 21:59 UTC, Vasar007 approved these changes

2018-11-23 04:20 UTC, levozavr commented on core/models.py
> +    release_date = models.DateField(blank=False)
Если я правильно помню то у ребят не стандартный формат хранения даты

2018-11-23 04:32 UTC, mehwhatever0 commented on core/models.py
> +    release_date = models.DateField(blank=False)
dd.mm.yyyy
![image](https://user-images.githubusercontent.com/43314216/48928603-dc93c180-eef1-11e8-83f3-cb96a8b9ac0d.png)

2018-11-23 13:27 UTC, levkovalenko approved these changes

2018-11-23 13:27 UTC, merged